CREATE TABLE Wallet (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    userId UUID NOT NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    coin DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
